/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.worker;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.logica_fabrica_stock_fabrica;
import modelo.Productos;
import persistencia.ProductosJpaController;
import vista.login.login;

/**
 *
 * @author reyes
 */
public class stock_fabrica extends javax.swing.JFrame {

    ProductosJpaController cProductos = new ProductosJpaController();
    logica_fabrica_stock_fabrica logicaF = new logica_fabrica_stock_fabrica();
    Productos cEdit;
    
    public static int contadorG = 0;
    public static int contadorP = 0;
    /**
     * Creates new form stock_fabrica
     */
    public stock_fabrica() {
        initComponents();
        this.setMinimumSize(new Dimension(1400, 900));
        this.setLocationRelativeTo(null);
        CrearModelo();
        Cargar_Informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bAgregar = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSUtileria = new javax.swing.JButton();
        btnSFabrica = new javax.swing.JButton();
        btnMPrimas = new javax.swing.JButton();
        btnObs = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 110, 1210, 740));

        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bAgregarL.png"))); // NOI18N
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 200, 50));

        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bPedidos.png"))); // NOI18N
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 83, 83));

        btnSUtileria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bStockU.png"))); // NOI18N
        btnSUtileria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUtileriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSUtileria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 83, 81));

        btnSFabrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bStockF.png"))); // NOI18N
        btnSFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSFabricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 82, 82));

        btnMPrimas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bStockM.png"))); // NOI18N
        btnMPrimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPrimasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 82, 80));

        btnObs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Admin_bObservaciones.png"))); // NOI18N
        btnObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObsActionPerformed(evt);
            }
        });
        getContentPane().add(btnObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 82, 84));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bExit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Fabrica_StockF.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de realizar la operacion?", "Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                List<Productos> listP = cProductos.findProductosEntities();
               
                String productoF1 = listP.get(0).getProdNombre();
                String productoF2 = listP.get(1).getProdNombre();
                int numeroo = tabla.getSelectedRow();
                String Nombree = (String) modelo.getValueAt(numeroo, 1);
                if (Nombree.equals(productoF1) && (contadorG < 3)) {
                    cEdit = cProductos.findProductos((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0));
                    int numero = tabla.getSelectedRow();
                    int cantidadS = (int) modelo.getValueAt(numero, 3);
                    //System.out.println(cantidadS);
                    cEdit.setProdCantidad(cantidadS + 300);
                    logicaF.reducirMP(0);
                    contadorG++;
                } else if (Nombree.equals(productoF1) && contadorG > 2) {
                    JOptionPane.showMessageDialog(null, "ya se agregaron demasiados lotes de graniplas por hoy");
                }

                if (Nombree.equals(productoF2) && (contadorP < 3)) {
                    cEdit = cProductos.findProductos((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0));
                    int numero = tabla.getSelectedRow();
                    int cantidadS = (int) modelo.getValueAt(numero, 3);
                    //  System.out.println(cantidadS);

                    cEdit.setProdCantidad(cantidadS + 60);
                    logicaF.reducirMP(1);
                    contadorP++;
                } else if (Nombree.equals(productoF2) && contadorP > 2) {
                    JOptionPane.showMessageDialog(null, "ya se agregaron demasiados lotes de pintura por hoy");
                }
                cProductos.edit(cEdit);
                System.out.println("Se actualizo");
                CrearModelo();
                Cargar_Informacion();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString() + "error");
                System.out.println("Error al actualizar");
            }
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        pedidos window = new pedidos();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnSUtileriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUtileriaActionPerformed
        stock_utileria window = new stock_utileria();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSUtileriaActionPerformed

    private void btnSFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSFabricaActionPerformed
        stock_fabrica window = new stock_fabrica();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSFabricaActionPerformed

    private void btnMPrimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPrimasActionPerformed
        mprimas window = new mprimas();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMPrimasActionPerformed

    private void btnObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObsActionPerformed
        observaciones window = new observaciones();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnObsActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        login window = new login();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_fabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_fabrica().setVisible(true);
            }
        });
    }
    
    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Codigo", "Nombre",
                        "Unidad", "Cantidad", "P. Comprado",
                        "P. Venta", "Proveedor"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    
    private void Cargar_Informacion(){
        try{
            Object o[]=null;
            List<Productos> listP = cProductos.findProductosEntities();
            int contadorr = 0;
            for (int i=0; i< listP.size(); i++){
                String productoF = listP.get(i).getProdDescripcion();
                String productoF2 = listP.get(0).getProdDescripcion();
                if(productoF.equals(productoF2)){
                    modelo.addRow(o);
                    modelo.setValueAt(listP.get(i).getProdCodigo(), contadorr, 0);
                    modelo.setValueAt(listP.get(i).getProdNombre(), contadorr, 1);
                   // modelo.setValueAt(listP.get(i).getProdDescripcion(), contadorr, 2);
                    modelo.setValueAt(listP.get(i).getProdUnidadMedida(), contadorr, 2);
                    modelo.setValueAt(listP.get(i).getProdCantidad(), contadorr, 3);
                    modelo.setValueAt(listP.get(i).getProdPrecioComprado(), contadorr, 4);
                    modelo.setValueAt(listP.get(i).getProdPrecioVenta(), contadorr, 5);
                    modelo.setValueAt(listP.get(i).getProNIT().getProNIT(), contadorr, 6);
                    contadorr++;
                }
            }                                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton btnMPrimas;
    private javax.swing.JButton btnObs;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnSFabrica;
    private javax.swing.JButton btnSUtileria;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
