/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.login;

import vista.admin.router;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;
import modelo.Accounts;
import org.apache.commons.codec.digest.DigestUtils;
import persistencia.AccountsJpaController;
import vista.seller.facturacion;
import vista.worker.pedidos;

/**
 *
 * @author reyes
 */
public class login extends javax.swing.JFrame {
    
    AccountsJpaController cAccounts = new AccountsJpaController();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setMinimumSize(new Dimension(1400, 900));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        txtMess = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUser.setText("admin");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 250, 50));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Entrar.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 740, 420, 60));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPass.setText("123");
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 250, 50));

        txtMess.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMess.setForeground(java.awt.Color.red);
        getContentPane().add(txtMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 682, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Inicio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userMD5=DigestUtils.sha256Hex(txtUser.getText());
        String passMD5=DigestUtils.sha256Hex(String.valueOf(txtPass.getPassword()));

        List<Accounts> listA = cAccounts.findAccountsEntities();
        Accounts userAccount = new Accounts();
        
        int userCheck = 0;
        for (int i = 0; i < listA.size(); i++) {
            if(listA.get(i).getAccUser().equals(userMD5)){
                userAccount = listA.get(i);
                userCheck = 1;
            }
        } 
        
        if(userCheck == 0){
            txtPass.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
            txtMess.setText("Username does not exist");
            txtUser.setBorder(BorderFactory.createLineBorder(Color.red, 1));
        } else{
            if(userAccount.getAccPass().equals(passMD5)){
                if (userAccount.getEmpDni().getEmpCargo().equals("admin")) {
                    router window = new router();
                    window.setVisible(true);
                    this.dispose();
                }else if (userAccount.getEmpDni().getEmpCargo().equals("seller")) {
                    facturacion window = new facturacion();
                    window.setVisible(true);
                    this.dispose();
                }else if (userAccount.getEmpDni().getEmpCargo().equals("worker")) {
                    pedidos window = new pedidos();
                    window.setVisible(true);
                    this.dispose();
                }
            }else{
                txtUser.setBorder(BorderFactory.createLineBorder(Color.gray, 1));
                txtMess.setText("Your password is wrong");
                txtPass.setBorder(BorderFactory.createLineBorder(Color.red, 1));
            }
        }      
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtMess;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
