/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Materiasprimas;
import modelo.Proveedores;
import persistencia.MateriasprimasJpaController;
import persistencia.ProveedoresJpaController;

/**
 *
 * @author reyes
 */
public class gestionar_mprimas extends javax.swing.JFrame {

    MateriasprimasJpaController cMateriasprimas = new MateriasprimasJpaController();
    ProveedoresJpaController cProveedores = new ProveedoresJpaController();
    Materiasprimas cEdit;
    
    /**
     * Creates new form gestionar_mprimas
     */
    public gestionar_mprimas() {
        initComponents();
        this.setMinimumSize(new Dimension(1400, 650));
        this.setLocationRelativeTo(null);
        CrearModelo();
        Cargar_Informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        bSeleccionar = new javax.swing.JButton();
        txtPrecioC = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        comboUnidad = new javax.swing.JComboBox<>();
        comboProv = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, 30));

        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bSeleccionar.png"))); // NOI18N
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 200, 50));

        txtPrecioC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 180, 30));

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bGuardar.png"))); // NOI18N
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 200, 50));

        tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 19, 810, 600));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, 30));

        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bActualizar.png"))); // NOI18N
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 200, 50));

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 30));

        comboUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Gal" }));
        getContentPane().add(comboUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 180, 30));

        comboProv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(comboProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Gestionar_MateriasPrimas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
        txtDescripcion.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
        comboUnidad.setSelectedItem(modelo.getValueAt(tabla.getSelectedRow(), 3).toString());
        txtCantidad.setText(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
        txtPrecioC.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
        comboProv.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());

        cEdit = cMateriasprimas.findMateriasprimas((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0));
    }//GEN-LAST:event_bSeleccionarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de realizar la operacion?", "Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                Materiasprimas c = new Materiasprimas();

                c.setMatNombre(txtNombre.getText());
                c.setMatDescripcion(txtDescripcion.getText());
                c.setMatUnidadMedida((String) comboUnidad.getSelectedItem());
                c.setMatCatidad(Integer.parseInt(txtCantidad.getText()));
                c.setMatPrecioComprado(Integer.parseInt(txtPrecioC.getText()));
                c.setProNIT(cProveedores.findProveedores(comboProv.getSelectedItem().toString()));

                cMateriasprimas.create(c);
                System.out.println("Los datos fueron guardados");

                CrearModelo();
                Cargar_Informacion();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                System.out.println("Problema el guardar datos");
            }
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro de realizar la operacion?", "Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            try{
                cEdit.setMatNombre(txtNombre.getText());
                cEdit.setMatDescripcion(txtDescripcion.getText());
                cEdit.setMatCatidad(Integer.parseInt(txtCantidad.getText()));
                cEdit.setMatPrecioComprado(Integer.parseInt(txtPrecioC.getText()));
                cEdit.setProNIT(cProveedores.findProveedores(comboProv.getSelectedItem().toString()));

                cMateriasprimas.edit(cEdit);
                System.out.println("Se actualizo");
                CrearModelo();
                Cargar_Informacion();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.toString() + "error");
                System.out.println("Error al actualizar");
            }
        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionar_mprimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionar_mprimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionar_mprimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionar_mprimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionar_mprimas().setVisible(true);
            }
        });
    }
    
    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Codigo", "Nombre", "Descripcion",
                        "Unidad", "Cantidad", "P. Comprado",
                        "Proveedor"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    
    private void Cargar_Informacion(){
        try{
            Object o[]=null;
            List<Materiasprimas> listP = cMateriasprimas.findMateriasprimasEntities();
            List<Proveedores> listProv = cProveedores.findProveedoresEntities();
            for (int i=0; i< listP.size(); i++){
                modelo.addRow(o);
                modelo.setValueAt(listP.get(i).getMatCodigo(), i, 0);
                modelo.setValueAt(listP.get(i).getMatNombre(), i, 1);
                modelo.setValueAt(listP.get(i).getMatDescripcion(), i, 2);
                modelo.setValueAt(listP.get(i).getMatUnidadMedida(), i, 3);
                modelo.setValueAt(listP.get(i).getMatCatidad(), i, 4);
                modelo.setValueAt(listP.get(i).getMatPrecioComprado(), i, 5);
                modelo.setValueAt(listP.get(i).getProNIT().getProNIT(), i, 6);                
            }                                            
            
            for (int i = 0; i < listProv.size(); i++) {
                comboProv.addItem(listProv.get(i).getProNIT());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboProv;
    private javax.swing.JComboBox<String> comboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioC;
    // End of variables declaration//GEN-END:variables
}
