/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import java.awt.Dimension;
import vista.seller.facturacion;
import vista.worker.pedidos;

/**
 *
 * @author reyes
 */
public class router extends javax.swing.JFrame {

    /**
     * Creates new form router
     */
    public router() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setMinimumSize(new Dimension(1000, 650));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdmin = new javax.swing.JButton();
        btnSeller = new javax.swing.JButton();
        btnWorker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(0, 0, 102));
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, 160));

        btnSeller.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        btnSeller.setForeground(new java.awt.Color(0, 0, 102));
        btnSeller.setText("Seller");
        btnSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 210, 160));

        btnWorker.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        btnWorker.setForeground(new java.awt.Color(0, 0, 102));
        btnWorker.setText("Worker");
        btnWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerActionPerformed(evt);
            }
        });
        getContentPane().add(btnWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 210, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/SmallWin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        gestionar window = new gestionar();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellerActionPerformed
        facturacion window = new facturacion();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSellerActionPerformed

    private void btnWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerActionPerformed
        pedidos window = new pedidos();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(router.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(router.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(router.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(router.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new router().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnSeller;
    private javax.swing.JButton btnWorker;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
