/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.seller;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.logica_venta_facturacion;
import modelo.Clientes;
import modelo.Detallesorden;
import modelo.Ordenes;
import modelo.Productos;
import persistencia.ClientesJpaController;
import persistencia.DetallesordenJpaController;
import persistencia.OrdenesJpaController;
import persistencia.ProductosJpaController;
import vista.login.login;

/**
 *
 * @author reyes
 */
public class facturacion extends javax.swing.JFrame {

    ProductosJpaController cProductos = new ProductosJpaController();
    ClientesJpaController cClientes = new ClientesJpaController();
    DetallesordenJpaController cDetalles = new DetallesordenJpaController();
    OrdenesJpaController cOrdenes = new OrdenesJpaController();
    public static Ordenes Ordennnn;
    
    /**
     * Creates new form facturacion
     */
    public facturacion() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setMinimumSize(new Dimension(1420, 950));
        this.setLocationRelativeTo(null); 
        CrearModelo();
        Cargar_Informacion_Combos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bCliente = new javax.swing.JButton();
        bDescuento = new javax.swing.JButton();
        comboClientes = new javax.swing.JComboBox<>();
        bFinalizar = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        comboColor = new javax.swing.JComboBox<>();
        comboProducto = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnObservaciones = new javax.swing.JButton();
        btnSFabrica = new javax.swing.JButton();
        btnSUtileria = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 1230, 480));

        bCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCliente.setText("Registrar - Modificar");
        bCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClienteActionPerformed(evt);
            }
        });
        getContentPane().add(bCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 780, -1, 30));

        bDescuento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bDescuento.setText("Eplicar Desc.");
        bDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(bDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 780, 149, 30));

        comboClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientesActionPerformed(evt);
            }
        });
        getContentPane().add(comboClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 190, 30));

        bFinalizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bFinalizar.setText("Finalizar");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(bFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 830, 130, 30));

        bPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bPagar.setText("Pagar");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });
        getContentPane().add(bPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 830, 130, 30));

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(58, 58, 128));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText("-");
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 780, 127, 30));

        labelDescuento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDescuento.setForeground(new java.awt.Color(58, 58, 128));
        labelDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuento.setText("0");
        getContentPane().add(labelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 720, 127, 30));

        labelSubtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(58, 58, 128));
        labelSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtotal.setText("-");
        getContentPane().add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 660, 127, 40));

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 103, 30));

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 95, 30));

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(58, 58, 128));
        txtCantidad.setText("0");
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 157, -1));

        comboColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 193, 30));

        comboProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(comboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 169, 30));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bExit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 90, 100));

        btnObservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Admin_bObservaciones.png"))); // NOI18N
        btnObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 80, 80));

        btnSFabrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bStockF.png"))); // NOI18N
        btnSFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSFabricaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 80, 80));

        btnSUtileria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bStockU.png"))); // NOI18N
        btnSUtileria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUtileriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSUtileria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 80, 80));

        btnFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/venta_bFacturacion.png"))); // NOI18N
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });
        getContentPane().add(btnFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Venta_Facturacion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClienteActionPerformed
        vista.admin.gestionar_clientes ventana = new vista.admin.gestionar_clientes();
        ventana.setVisible(true);
    }//GEN-LAST:event_bClienteActionPerformed

    private void bDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescuentoActionPerformed
        ClientesJpaController sClientes = new ClientesJpaController();
        labelDescuento.setText(String.valueOf(sClientes.findClientes(String.valueOf(comboClientes.getSelectedItem())).getCliDescuento()));
        logica.logica_venta_facturacion.totalL();
    }//GEN-LAST:event_bDescuentoActionPerformed

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
                if(contadorAgregar > 0){
                    if (pago.ordenN == 1) {
                        //    for (int i = 0; i < contadorAgregar; i++) {System.out.println(modelo.getValueAt(i, 0));}}}
                try {
                    for (int i = 0; i < contadorAgregar; i++) {
                        List<Productos> listP = cProductos.findProductosEntities();
                        String prodN = (String) modelo.getValueAt(i, 0);
                        int cantidadd = (Integer) modelo.getValueAt(i, 2);
                        int contadorw = 0;

                       // System.out.println("proN: " + prodN);
                        for (int j = 0; j < listP.size(); j++) {
                            if (prodN == listP.get(j).getProdNombre()) {
                               // System.out.println("Se agrego " + listP.get(i).getProdNombre());
                                contadorw = listP.get(j).getProdCodigo();
                            }
                        }
                       // System.out.println("Contadorw: " + contadorw);
                        String color = (String) modelo.getValueAt(i, 1);

                        Detallesorden c = new Detallesorden();
                        // OrdenesJpaController cOrdenes = new OrdenesJpaController();
                        int num = cOrdenes.getOrdenesCount();
                        Ordenes ordenn = cOrdenes.findOrdenes(num);
                        c.setOrdCodigo(ordenn);
                        c.setProdCodigo(cProductos.findProductos(contadorw));
                        c.setDetCantidad(cantidadd);
                        c.setDetDescripcion(color);
                        cDetalles.create(c);

                        //  logica_venta_facturacion.crearDeta(Prod,cantidadd,colorr);
                        Productos pEdit = cProductos.findProductos(contadorw);
                        System.out.println("Se realizo detalles");
                        int cantidaddd = pEdit.getProdCantidad();
                        pEdit.setProdCantidad(cantidaddd - cantidadd);
                        cProductos.edit(pEdit);
                    }

                    // CrearModelo();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    System.out.println("Error al crear los detalles de ordenes");
                }
            }else{
                JOptionPane.showMessageDialog(null, "No ha realizado pago");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue al menos un producto");
        }
        pago.ordenN = 0;

    }//GEN-LAST:event_bFinalizarActionPerformed

    
    
    public static int Descuento;
    public static String NITCliente;
    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        try{
            if(contadorAgregar > 0){
                NITCliente = String.valueOf(comboClientes.getSelectedItem());
                Descuento = Integer.parseInt(labelDescuento.getText());
                pago ventana = new pago();
                ventana.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "No hay ningun producto para pagar");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error al pagar");
        }
    }//GEN-LAST:event_bPagarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        try{
            if(contadorAgregar > 0){
                int numero = (int) tabla.getValueAt(tabla.getSelectedRow(), 5);
                subtotal = subtotal - numero;

                modelo.removeRow(tabla.getSelectedRow());
                contadorAgregar --;
                // System.out.println(subtotal);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Selecciona un producto para eliminar.");
        }
        labelSubtotal.setText(String.valueOf(subtotal));
        logica_venta_facturacion.totalL();
    }//GEN-LAST:event_bEliminarActionPerformed

    
    int contadorAgregar = 0;
    public static int subtotal = 0;
    int total = 0;
    
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        List<Productos> listP = cProductos.findProductosEntities();
        int codigo = 0;
        String prodNombre = (String) comboProducto.getSelectedItem();
        for (int i = 0; i < listP.size(); i++) {
            if (listP.get(i).getProdNombre() == prodNombre) {
                codigo = listP.get(i).getProdCodigo();
            }
        }
        String prodColor = (String) comboColor.getSelectedItem();
        int cantidadP = Integer.parseInt(txtCantidad.getText());
        System.out.println(cantidadP);
        String unidad = cProductos.findProductos(codigo).getProdUnidadMedida();
        int valorU = cProductos.findProductos(codigo).getProdPrecioVenta();
        int totalP = cantidadP * valorU;
        // JOptionPane.showMessageDialog(null, cantidadP);
        int cantidadProd = cProductos.findProductos(codigo).getProdCantidad();
        if (cantidadP > 0) {
            if (cantidadP <= cantidadProd) {

                logica_venta_facturacion.agregarItemTabla(contadorAgregar, prodNombre, prodColor, cantidadP, unidad, valorU, totalP);
                contadorAgregar++;
                logica_venta_facturacion.subtotalL(contadorAgregar, totalP); //Subtotal
                logica_venta_facturacion.totalL();
            } else {
                JOptionPane.showMessageDialog(null, "No existe en stock la cantidad solicitada de este producto. \n"
                    + "Solo quedan: " + cantidadProd + " Unidades de " + prodNombre);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad mayor a 0.");
        }
        //JOptionPane.showMessageDialog(null, totalP);
        
    }//GEN-LAST:event_bAgregarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        login window = new login();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        facturacion window = new facturacion();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFactActionPerformed

    private void btnSUtileriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUtileriaActionPerformed
        stock_utileria window = new stock_utileria();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSUtileriaActionPerformed

    private void btnSFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSFabricaActionPerformed
        stock_fabrica window = new stock_fabrica();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSFabricaActionPerformed

    private void btnObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservacionesActionPerformed
        observacion window = new observacion();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnObservacionesActionPerformed

    private void comboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturacion().setVisible(true);
            }
        });
    }
    
    public static DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Producto", "Color", "Cantidad",
                        "Unidad", "Valor Unitario", "Valor Total",}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    private void Cargar_Informacion_Combos(){
        try{
            List<Productos> listP = cProductos.findProductosEntities();
            
            for (int i=0; i< listP.size(); i++){
                comboProducto.addItem(listP.get(i).getProdNombre());     
            } 
            
            List<Clientes> listC = cClientes.findClientesEntities();
            
            for (int i=0; i< listC.size(); i++){
                comboClientes.addItem(listC.get(i).getCliNIT());     
            }
            
            comboColor.addItem("-");
            comboColor.addItem("123");
            comboColor.addItem("132");
            comboColor.addItem("213");
            comboColor.addItem("231");
            comboColor.addItem("312");
            comboColor.addItem("321");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bCliente;
    private javax.swing.JButton bDescuento;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bPagar;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnObservaciones;
    private javax.swing.JButton btnSFabrica;
    private javax.swing.JButton btnSUtileria;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelDescuento;
    public static javax.swing.JLabel labelSubtotal;
    public static javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
