/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.seller;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Ordenes;
import persistencia.ClientesJpaController;
import persistencia.OrdenesJpaController;

/**
 *
 * @author reyes
 */
public class pago extends javax.swing.JFrame {

    OrdenesJpaController cOrdenes = new OrdenesJpaController();
    ClientesJpaController cClientes = new ClientesJpaController();
    
    java.util.Date fecha = new Date();
    String strDateFormat = "dd/MM/y";
    SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
    //System.out.println(objSDF.format(fecha));
    String fechaHoy = objSDF.format(fecha);
    
    
    
    public static Ordenes Orden;
    public static int ordenN = 0;
    
    /**
     * Creates new form pago
     */
    public pago() {
        initComponents();
        this.setMinimumSize(new Dimension(1000, 650));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        comboTP = new javax.swing.JComboBox<>();
        bCancelar = new javax.swing.JButton();
        bEjecutar = new javax.swing.JButton();
        dateFD = new com.toedter.calendar.JDateChooser();
        dateFP = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 260, 30));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(58, 58, 128));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Bancario", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, 40));

        comboTP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTP.setForeground(new java.awt.Color(58, 58, 128));
        comboTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        getContentPane().add(comboTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 160, 40));

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bCancelar.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 531, 200, 50));

        bEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bEjecutar.png"))); // NOI18N
        bEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(bEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 531, 200, 50));
        getContentPane().add(dateFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 230, 30));
        getContentPane().add(dateFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Venta_Pago.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEjecutarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Esta seguro que desea realizar el pago con los datos introducidos?", "Confirmacion",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                Ordenes c = new Ordenes();

                Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(fechaHoy);
                c.setOrdFechaOrden(date1);

                //  Date date2=new SimpleDateFormat("dd/MM/yyyy").parse(txtFD.getText());
                c.setOrdFechaDespacho(dateFD.getDate());

                if(comboTP.getSelectedItem() == "Credito"){
                    //      Date date3=new SimpleDateFormat("dd/MM/yyyy").parse(txtFP.getText());
                    c.setOrdFechaPago(dateFP.getDate());
                } else {
                    Date date3=new SimpleDateFormat("dd/MM/yyyy").parse(fechaHoy);
                    c.setOrdFechaPago(date3);
                }

                c.setOrdDireccionEnvio(txtDireccion.getText());
                c.setOrdTelefonoEnvio(txtTelefono.getText());
                c.setOrdComentario("-");  //Comentario sera el indicador si ya se despacho la orden o no
                // En este caso como apenas esta haciendo la orden le damos el varlo "-" para indicar
                // que todavia no se ha hecho

                //   venta_facturacion ventanaF = new venta_facturacion();
                //  int Descuento = Integer.parseInt(ventanaF.Descuento);
                //  String Cliente = ventanaF.NITCliente;
                c.setOrdDescuento(facturacion.Descuento);
                c.setOrdTipoPago((String) comboTP.getSelectedItem());

                // clie.cliNIT = Cliente;
                c.setCliNIT(cClientes.findClientes(facturacion.NITCliente));
                c.setOrdEstado(0);
                cOrdenes.create(c);
                ordenN = 1;
                System.out.println("Los datos fueron guardados");
                this.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                System.out.println("Problema el guardar datos");
            }
        }
        

    }//GEN-LAST:event_bEjecutarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEjecutar;
    private javax.swing.JComboBox<String> comboTP;
    private com.toedter.calendar.JDateChooser dateFD;
    private com.toedter.calendar.JDateChooser dateFP;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
